name: CI

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "student2-week3-ci-cd" ]

jobs:
  build-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker versions
        run: |
          docker --version
          docker compose version

      - name: Build containers
        run: docker compose build

      - name: Start containers (smoke test)
        run: docker compose up -d

      - name: Show running containers
        run: docker ps -a

      - name: Logs (db + app)
        run: |
          docker logs sis_db || true
          docker logs sis_app || true

      - name: Stop containers
        if: always()
        run: docker compose down -v
